# Generated by Django 3.0.6 on 2020-05-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='num_stars',
        ),
    ]
