# Generated by Django 3.0.6 on 2020-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_num_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(default=0),
        ),
    ]
